[package]
name = "pushpin"
version = "1.41.0-dev"
authors = ["Justin Karneges <jkarneges@fastly.com>"]
description = "Reverse proxy for realtime web services"
repository = "https://github.com/fastly/pushpin"
readme = "README.md"
license = "Apache-2.0"
edition = "2018"
default-run = "pushpin"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = "none"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
aegis = "^0.4.2"
arrayvec = "0.7"
backtrace = { version = "0.3", features = ["cpp_demangle"] }
base64 = "0.13"
clap = { version = "=4.3.24", features = ["cargo", "string", "wrap_help", "derive"] }
config = "0.14"
httparse = "1.7"
ipnet = "2"
jsonwebtoken = "8"
libc = "0.2"
log = "0.4"
miniz_oxide = "0.6"
mio = { version = "1", features = ["os-poll", "os-ext", "net"] }
openssl = "=0.10.66"
paste = "1.0"
rustls = "0.21"
rustls-native-certs = "0.6"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
sha1 = "0.10"
signal-hook = "0.3"
slab = "0.4"
socket2 = "0.4"
stats-emitter = { git = "ssh://git@github.com/fastly/stats-emitter-rs" }
thiserror = "1.0"
time = { version = "0.3.36", features = ["formatting", "local-offset", "macros"] }
url = "2.3"
zmq = "0.9"

# for stats-emitter
anyhow = "^1.0.42"
ctor = "^0.1.20"
http = "^0.2.7"
hyper = { version = "^0.14.11", features = ["full"] }
hyper-openssl = "0.9.1"
lazy_static = "^1.4.0"
pin-project = "1.0.8"
prometheus = "^0.12.0"
prometheus-utils = "^0.6.1"
rand = "^0.8.4"
static_assertions = "^1.1.0"
tokio = { version = "^1.13.1", features = ["full"] }
toml = "^0.5.8"
tracing = "^0.1.26"
tracing-subscriber = "^0.3"

# for seccomp
nix = "^0.22.0"
memoffset = "^0.6.4"

[dev-dependencies]
criterion = "0.5"
env_logger = { version = "0.9", default-features = false }
test-log = "0.2"

# for stats-emitter
bincode = "^1.3.3"
maplit = "^1.0.2"
tempdir = "^0.3.7"
wiremock = "^0.5.6"

[build-dependencies]
pkg-config = "0.3"
time = { version = "0.3.36", features = ["formatting", "local-offset", "macros"] }
cbindgen = "0.27"

[[bench]]
name = "server"
harness = false

[[bench]]
name = "client"
harness = false

[[bin]]
name = "pushpin-connmgr"
test = false
bench = false

[[bin]]
name = "m2adapter"
test = false
bench = false

[[bin]]
name = "pushpin-proxy"
test = false
bench = false

[[bin]]
name = "pushpin-handler"
test = false
bench = false

[[bin]]
name = "pushpin-legacy"
test = false
bench = false

[[bin]]
name = "pushpin"
test = false
bench = false

[[bin]]
name = "pushpin-publish"
test = false
bench = false

[lints.rust]

unexpected_cfgs = { level = "warn", check-cfg = ['cfg(qt_lib_prefix, values("Qt", "Qt6", "Qt5"))'] }
