#############################################################################
# Makefile for building: pushpin
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  pushpin.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile pushpin.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-m2adapter \
		sub-proxy \
		sub-handler \
		sub-tools-publish


sub-m2adapter-qmake_all:  FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile
	cd m2adapter/ && $(MAKE) -f Makefile qmake_all
sub-m2adapter: FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile
sub-m2adapter-make_first: FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-m2adapter-all: FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-m2adapter-clean: FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-m2adapter-distclean: FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-m2adapter-install_subtargets: FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-m2adapter-uninstall_subtargets: FORCE
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-proxy-qmake_all:  FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile
	cd proxy/ && $(MAKE) -f Makefile qmake_all
sub-proxy: FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile
sub-proxy-make_first: FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-proxy-all: FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-proxy-clean: FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-proxy-distclean: FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-proxy-install_subtargets: FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-proxy-uninstall_subtargets: FORCE
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-handler-qmake_all:  FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile
	cd handler/ && $(MAKE) -f Makefile qmake_all
sub-handler: FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile
sub-handler-make_first: FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-handler-all: FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-handler-clean: FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-handler-distclean: FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-handler-install_subtargets: FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-handler-uninstall_subtargets: FORCE
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tools-publish-qmake_all:  FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile
	cd tools/publish/ && $(MAKE) -f Makefile qmake_all
sub-tools-publish: FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile
sub-tools-publish-make_first: FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-tools-publish-all: FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-tools-publish-clean: FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-tools-publish-distclean: FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tools-publish-install_subtargets: FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-tools-publish-uninstall_subtargets: FORCE
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: pushpin.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		conf.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		pushpin.pro
	$(QMAKE) -o Makefile pushpin.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
conf.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
pushpin.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile pushpin.pro

qmake_all: sub-m2adapter-qmake_all sub-proxy-qmake_all sub-handler-qmake_all sub-tools-publish-qmake_all FORCE

make_first: sub-m2adapter-make_first sub-proxy-make_first sub-handler-make_first sub-tools-publish-make_first FORCE
all: sub-m2adapter-all sub-proxy-all sub-handler-all sub-tools-publish-all FORCE
clean: sub-m2adapter-clean sub-proxy-clean sub-handler-clean sub-tools-publish-clean FORCE
distclean: sub-m2adapter-distclean sub-proxy-distclean sub-handler-distclean sub-tools-publish-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-m2adapter-install_subtargets sub-proxy-install_subtargets sub-handler-install_subtargets sub-tools-publish-install_subtargets FORCE
uninstall_subtargets: sub-m2adapter-uninstall_subtargets sub-proxy-uninstall_subtargets sub-handler-uninstall_subtargets sub-tools-publish-uninstall_subtargets FORCE

sub-m2adapter-check:
	@test -d m2adapter/ || mkdir -p m2adapter/
	cd m2adapter/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/m2adapter/m2adapter.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-proxy-check:
	@test -d proxy/ || mkdir -p proxy/
	cd proxy/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/proxy/proxy.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-handler-check:
	@test -d handler/ || mkdir -p handler/
	cd handler/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/handler/handler.pro -o Makefile ) && $(MAKE) -f Makefile check
sub-tools-publish-check:
	@test -d tools/publish/ || mkdir -p tools/publish/
	cd tools/publish/ && ( test -e Makefile || $(QMAKE) /home/justin/dev/pushpin/tools/publish/publish.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-m2adapter-check sub-proxy-check sub-handler-check sub-tools-publish-check
install_runnerlibfiles: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/lib/pushpin/runner || mkdir -p $(INSTALL_ROOT)/usr/local/lib/pushpin/runner
	-$(INSTALL_FILE) /home/justin/dev/pushpin/runner/processmanager.py $(INSTALL_ROOT)/usr/local/lib/pushpin/runner/
	-$(INSTALL_FILE) /home/justin/dev/pushpin/runner/services.py $(INSTALL_ROOT)/usr/local/lib/pushpin/runner/
	-$(INSTALL_FILE) /home/justin/dev/pushpin/runner/runner.py $(INSTALL_ROOT)/usr/local/lib/pushpin/runner/

uninstall_runnerlibfiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/lib/pushpin/runner/runner.py
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/lib/pushpin/runner/services.py
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/lib/pushpin/runner/processmanager.py
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/lib/pushpin/runner/ 


install_runnerconfigfiles: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/etc/pushpin/runner || mkdir -p $(INSTALL_ROOT)/usr/local/etc/pushpin/runner
	-$(INSTALL_FILE) /home/justin/dev/pushpin/runner/mongrel2.conf.template $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/
	-$(INSTALL_FILE) /home/justin/dev/pushpin/runner/m2adapter.conf.template $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/
	-$(INSTALL_FILE) /home/justin/dev/pushpin/runner/zurl.conf.template $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/
	-$(INSTALL_DIR) /home/justin/dev/pushpin/runner/certs $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/

uninstall_runnerconfigfiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/certs
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/zurl.conf.template
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/m2adapter.conf.template
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/mongrel2.conf.template
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/etc/pushpin/runner/ 


install_runnerbinfiles: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/bin || mkdir -p $(INSTALL_ROOT)/usr/local/bin
	cp -f pushpin.inst $(INSTALL_ROOT)/usr/local/bin/pushpin


install_pushpinconfigfiles: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/etc/pushpin || mkdir -p $(INSTALL_ROOT)/usr/local/etc/pushpin
	-$(INSTALL_FILE) /home/justin/dev/pushpin/examples/config/internal.conf $(INSTALL_ROOT)/usr/local/etc/pushpin/

uninstall_pushpinconfigfiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/local/etc/pushpin/internal.conf
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/etc/pushpin/ 


install_routes: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/etc/pushpin || mkdir -p $(INSTALL_ROOT)/usr/local/etc/pushpin
	test -e $(INSTALL_ROOT)/usr/local/etc/pushpin/routes || cp -f examples/config/routes $(INSTALL_ROOT)/usr/local/etc/pushpin/routes


install_pushpinconf: FORCE
	@test -d $(INSTALL_ROOT)/usr/local/etc/pushpin || mkdir -p $(INSTALL_ROOT)/usr/local/etc/pushpin
	test -e $(INSTALL_ROOT)/usr/local/etc/pushpin/pushpin.conf || cp -f pushpin.conf.inst $(INSTALL_ROOT)/usr/local/etc/pushpin/pushpin.conf


install: install_subtargets install_runnerlibfiles install_runnerconfigfiles install_runnerbinfiles install_pushpinconfigfiles install_routes install_pushpinconf  FORCE

uninstall: uninstall_runnerlibfiles uninstall_runnerconfigfiles uninstall_pushpinconfigfiles  uninstall_subtargets FORCE

FORCE:

