#!/usr/bin/env python

import sys
import os
from setproctitle import setproctitle
from runner import runner

setproctitle("pushpin")

exedir = os.path.dirname(os.path.realpath(__file__))

config_file_list = list()
for arg in sys.argv:
	if arg.startswith("--config="):
		config_file_list.append(arg[9:])
		break

# config file in same dir as executable
config_file_list.append(os.path.join(exedir, "pushpin.conf"))

# config file in /etc
config_file_list.append("/etc/pushpin/pushpin.conf")

config_file = None
for f in config_file_list:
	if os.path.isfile(f):
		config_file = f
		break

if not config_file:
	print "Error: no configuration file found. Tried %s" % ", ".join(config_file_list)
	sys.exit(1)

runner.run(exedir, config_file)
