<qconf>
 <name>Pushpin</name>
 <profile>pushpin.pro</profile>
 <moddir>qcm</moddir>
 <dep type='qt5'>
  <required/>
 </dep>
 <dep type='conf'>
  <required/>
 </dep>
 <dep type='pkg' name='libzmq' pkgname='libzmq' version='>=2.0'>
  <required/>
 </dep>
 <dep type='pkg' name='libcrypto' pkgname='libcrypto' version='>=1.0'>
  <required/>
 </dep>
 <dep type='pkg' name='libssl' pkgname='libssl' version='>=1.0'>
  <required/>
 </dep>
 <dep type='cargo'>
  <required/>
 </dep>
</qconf>
