#ifndef RUST_ENCRYPT_H
#define RUST_ENCRYPT_H

// NOTE: must match values on the rust side
#define ENCRYPT_ERROR_INVALID_INPUT 1
#define ENCRYPT_ERROR_UNSUPPORTED_ALGORITHM 2
#define ENCRYPT_ERROR_BAD_FORMAT 3
#define ENCRYPT_ERROR_INVALID_DATA 4

#define ENCRYPT_KEY_SIZE 16

#endif
