QMAKE_CXXFLAGS += $$(CXXFLAGS)
QMAKE_CFLAGS += $$(CFLAGS)
QMAKE_LFLAGS += $$(LDFLAGS)

CPP_DIR = $$PWD/../cpp
QZMQ_DIR = $$CPP_DIR/qzmq
RUST_DIR = $$PWD/../rust

INCLUDEPATH += $$CPP_DIR
INCLUDEPATH += $$QZMQ_DIR/src

DEFINES += NO_IRISNET

INCLUDEPATH += $$RUST_DIR/include

SOURCES += $$PWD/main.c
