#!/bin/sh
set -e
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/pushpin" ] ; then
	invoke-rc.d pushpin stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper rm_conffile /etc/pushpin/internal.conf 1.8.0-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/pushpin 1.9.0-2\~ -- "$@"
# End automatically added section
