QMAKE_CXXFLAGS += $$(CXXFLAGS)
QMAKE_CFLAGS += $$(CFLAGS)
QMAKE_LFLAGS += $$(LDFLAGS)

SRC_DIR = $$PWD/..
CPP_DIR = $$PWD/../../cpp
QZMQ_DIR = $$CPP_DIR/qzmq

INCLUDEPATH += $$SRC_DIR
INCLUDEPATH += $$CPP_DIR
INCLUDEPATH += $$QZMQ_DIR/src

DEFINES += NO_IRISNET

HEADERS += \
	$$SRC_DIR/app.h

SOURCES += \
	$$SRC_DIR/app.cpp \
	$$SRC_DIR/main.cpp
