#! /bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
  purge)
    # we mimic dpkg as closely as possible, so we remove configuration
    # files with dpkg backup extensions too:
    ### Some of the following is from Tore Anderson:
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist;  do
	rm -f /etc/pushpin/pushpin.conf$ext
    done

    # remove the configuration file itself
    rm -f /etc/pushpin/pushpin.conf

    # and finally clear it out from the ucf database
    if which ucf >/dev/null; then
        ucf --purge /etc/pushpin/pushpin.conf
    fi
    if which ucfr >/dev/null; then
        ucfr --purge pushpin /etc/pushpin/pushpin.conf
    fi
esac

# Originally added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d pushpin remove >/dev/null
fi

# Originally added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper rm_conffile /etc/pushpin/internal.conf 1.8.0-1\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/default/pushpin 1.9.0-2\~ -- "$@"

#DEBHELPER#

exit 0
