QMAKE_CXXFLAGS += $$(CXXFLAGS)
QMAKE_CFLAGS += $$(CFLAGS)
QMAKE_LFLAGS += $$(LDFLAGS)

SRC_DIR = $$PWD/..
CORE_DIR = $$PWD/../../corelib

INCLUDEPATH += $$SRC_DIR
INCLUDEPATH += $$CORE_DIR

DEFINES += NO_IRISNET

HEADERS += \
	$$SRC_DIR/app.h

SOURCES += \
	$$SRC_DIR/app.cpp \
	$$SRC_DIR/main.cpp
