#!/usr/bin/env python3

import argparse
from collections import namedtuple
import gzip
from http.client import HTTPConnection
from io import BytesIO
import json
import logging
import os
import string
import sys
import time
import traceback


PKG_VERSION = '1.0.0'

PUSHPIN_ENABLED_FLAG = 'loader-pushpin-enabled'
GRIP_ENABLED_FLAG = 'loader-pushpin-grip-enabled'
WOH_ENABLED_FLAG = 'loader-pushpin-woh-enabled'
ACO_ENABLED_FLAG = 'loader-pushpin-aco-enabled'
GRIP_ENABLED_FLAG_PREFIX = 'loader-pushpin-backend-grip-enabled:'
WOH_ENABLED_FLAG_PREFIX = 'loader-pushpin-backend-woh-enabled:'

alphanumerics = string.ascii_lowercase + string.ascii_uppercase + string.digits
Response = namedtuple('Response', 'status data etag')


class Service:
    def __init__(self, data, grip_enabled, woh_enabled, aco_enabled, backend_flags):
        self.data = data
        self.id = data['service']
        self.grip_enabled = grip_enabled
        self.woh_enabled = woh_enabled
        self.aco_enabled = aco_enabled
        self.backend_flags = backend_flags


class ValidationError(Exception):
    pass


def validate_id(s):
    if len(s) < 1 or len(s) > 63:
        raise ValidationError(
            'id must have a length between 1 and 63 characters')

    for c in s:
        if c not in '._-' and c not in alphanumerics:
            raise ValidationError('id cannot contain: {}'.format(repr(c)))

    return s


def validate_host(s):
    if len(s) < 1 or len(s) > 255:
        raise ValidationError(
            'host must have a length between 1 and 255 characters')

    for c in s:
        if c not in '._-' and c not in alphanumerics:
            raise ValidationError('host cannot contain: {}'.format(repr(c)))

    return s


class HeavenlyClient(object):
    def __init__(self):
        self.conn = None

    def request(self, url, accept, inm=None):
        # Use an established connection, open a new one if that fails.
        for reuse in (True, False):
            if reuse and self.conn is None:
                continue
            if not reuse:
                self.conn = None
                self.conn = HTTPConnection('localhost:8001')
            try:
                return self.request_on_conn(self.conn, url, accept, inm)
            except Exception:
                if not reuse:
                    raise

    def request_on_conn(self, conn, url, accept, inm):
        headers = {
            'Accept-Encoding': 'gzip',
            'Accept': accept,
            'Host': 'fastly-config-loader-2',
            'User-Agent': 'pushpin-loader/' + PKG_VERSION,
            'Fastly-CDN': 'fastly',
            'Fastly-Debug': '1',
        }
        headers['Heavenly-Canary'] = '0'
        if inm is not None:
            headers['If-None-Match'] = inm

        nredirs = 0
        while True:
            conn.request('GET', url, None, headers)
            resp = conn.getresponse()
            data = resp.read()

            location = resp.getheader('Location')
            if location and location.startswith('/'):
                url = location
                nredirs += 1
                if nredirs > 5:
                    raise IOError('Too many redirects')
                continue
            break

        if resp.status == 304:
            return Response(304, None, resp.getheader('ETag'))

        content_encoding = resp.getheader('Content-Encoding')
        if content_encoding:
            if content_encoding.lower() != 'gzip':
                raise IOError(
                    'Surprising Content-Encoding {}'.format(content_encoding))
            data = gzip.GzipFile(fileobj=BytesIO(data)).read()

        data = data.decode('utf-8')

        return Response(resp.status, data, resp.getheader('ETag'))


def fetch_service_backends():
    """
    Returns {service_id: [backend]}.
    """
    client = HeavenlyClient()

    logging.info('fetching service manifest')

    resp = client.request('/config/service/', 'application/json')
    services = json.loads(resp.data)

    pushpin_services = []

    for (service_id, service) in services.items():
        assert(service_id == service['service'])

        features = service.get('features', {})

        pushpin_enabled = features.get(PUSHPIN_ENABLED_FLAG, '0') == '1'
        grip_enabled = features.get(GRIP_ENABLED_FLAG, '0') == '1'
        woh_enabled = features.get(WOH_ENABLED_FLAG, '0') == '1'
        aco_enabled = features.get(ACO_ENABLED_FLAG, '0') == '1'

        backend_flags = {}

        for (k, v) in features.items():
            if k.startswith(GRIP_ENABLED_FLAG_PREFIX):
                offset = len(GRIP_ENABLED_FLAG_PREFIX)
                flag = 'grip-enabled'
            elif k.startswith(WOH_ENABLED_FLAG_PREFIX):
                offset = len(WOH_ENABLED_FLAG_PREFIX)
                flag = 'woh-enabled'
            else:
                continue

            backend_name = k[offset:]

            if backend_name not in backend_flags:
                backend_flags[backend_name] = {}

            backend_flags[backend_name][flag] = v

        if pushpin_enabled:
            pushpin_services.append(Service(service, grip_enabled, woh_enabled, aco_enabled, backend_flags))

    logging.debug('found {} services with pushpin enabled'.format(len(pushpin_services)))

    service_backends = {}

    for (i, service) in enumerate(pushpin_services):
        service_id = service.id
        version = service.data['version']

        logging.debug('fetching backends for service {} ({}/{})'.format(service_id,
              i + 1, len(pushpin_services)))

        resp = client.request(
            '/config/service/{}/version/{}/backends'.format(service_id, version), 'application/json')
        backends = json.loads(resp.data)['backends']

        # apply the backend-specific loader flags to the backend object
        for (backend_name, flags) in service.backend_flags.items():
            for backend in backends:
                if backend['name'] == backend_name:
                    for (k, v) in flags.items():
                        backend['loader-{}'.format(k)] = v
                    break

        # apply service-level flags to backends
        for backend in backends:
            if service.grip_enabled:
                backend['loader-grip-enabled'] = '1'
            if service.woh_enabled:
                backend['loader-woh-enabled'] = '1'

        service_backends[service_id] = (service, backends)

    return service_backends


def make_routes(service, backend):
    service_id = validate_id(service.id)
    backend_name = validate_id(backend['name'])
    host = validate_host(backend['address'])

    target = '{}:{}'.format(host, backend['port'])

    if int(backend.get('use_ssl', '0')):
        target += ',ssl'

    override_host = backend.get('override_host', '')
    if override_host:
        override_host = validate_host(override_host)
        target += ',host={}'.format(override_host)

    if int(backend.get('loader-woh-enabled', '0')):
        target += ',over_http'

    routes = []

    if int(backend.get('loader-grip-enabled', '0')):
        cond_opts = 'prefix=g:ck:{}:'.format(service_id)
        if service.aco_enabled:
            cond_opts += ',aco'

        routes.append('id=gr:{}:{},{} {}'.format(service_id, backend_name, cond_opts, target))
        routes.append('id=gr:ht:{}:{},{} {}'.format(service_id, backend_name, cond_opts, target))
        routes.append('id=gr:ws:{}:{},{} {}'.format(service_id, backend_name, cond_opts, target))
    else:
        routes.append('id={}:{},no_grip {}'.format(service_id, backend_name, target))
        routes.append('id=ws:{}:{},no_grip {}'.format(service_id, backend_name, target))
        routes.append('id=ws:{}:{}--{},no_grip {}'.format(service_id, service_id, backend_name, target))
        routes.append('id=ws:{}:{}--F_{},no_grip {}'.format(service_id, service_id, backend_name, target))

    return routes


def write_routes(routes, routes_file):
    """
    Returns True if routes file was changed.
    """
    newdata = ''
    for route in routes:
        newdata += route + '\n'

    try:
        with open(routes_file, 'r', encoding='utf-8') as f:
            curdata = f.read()
    except Exception:
        # failed to read original routes. no big deal
        curdata = ''

    if newdata != curdata:
        tmpfile = '{}.tmp'.format(routes_file)

        with open(tmpfile, 'w', encoding='utf-8') as f:
            f.write(newdata)

        os.rename(tmpfile, routes_file)

        return True
    else:
        return False


def update_routes(routes_file):
    routes = []

    routes.append('pushpin.healthcheck.test test')

    for service, backends in fetch_service_backends().values():
        for backend in backends:
            try:
                routes.extend(make_routes(service, backend))
            except Exception as e:
                logging.warning(
                    'failed to make route for service {} backend {}: {}'.format(service.id, repr(backend['name']), e))

    if write_routes(routes, routes_file):
        logging.info('wrote {}'.format(routes_file))
    else:
        logging.debug('no changes')


def main():
    parser = argparse.ArgumentParser(
        description='Fetch backends from Heavenly and write Pushpin routes file.')
    parser.add_argument('--log-level', metavar='N', type=int,
                        dest='log_level', default=2, help='log level')
    parser.add_argument('--output', metavar='FILENAME', dest='output',
                        default='routes', help='location of routes file (default: ./routes)')
    parser.add_argument('--loop', metavar='SECONDS', type=int,
                        dest='loop', help='repeat the process on an interval')

    args = parser.parse_args()

    log_level = [logging.ERROR, logging.WARNING, logging.INFO, logging.DEBUG][args.log_level]

    logging.basicConfig(stream=sys.stdout, level=log_level)

    routes_file = args.output

    sleep_time = 0
    if args.loop:
        sleep_time = args.loop

    while True:
        try:
            update_routes(routes_file)
        except Exception:
            logging.exception('update_routes failed')

        if not sleep_time:
            break

        # whether success or fail, sleep before acting again
        logging.debug('sleeping for {}s'.format(sleep_time))
        time.sleep(sleep_time)


main()
